name: Deploy to AWS

on:
  push:
    branches: [ dev ]

jobs:
  frontend_deployment:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install

    - name: Build site
      working-directory: ./frontend
      run: yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy build to S3 bucket
      working-directory: ./frontend
      run: aws s3 sync ./build s3://calenderly
