name: Running Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Check the linter
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run eslint ./
    
    - name: Run tests
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
