name: Running Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: yarn install

    - name: Check the linter
      working-directory: ./backend
      run: yarn lint
    
    - name: Run tests
      working-directory: ./backend
      run: yarn run jest
